name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      # There is an error "no such option: --system" when running
      # please with python installed this way.
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.8'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install python
        run: sudo apt update && sudo apt install -y python3 python3-pip

      - name: Set up Please
        uses: sagikazarmark/setup-please-action@v0

      - name: Build
        run: plz build //...

      - name: Test
        run: plz test //...
